### ISSUE TITLE
Config replaces default config

### ISSUE THREAD

**Issue by fletchgqc** [dustinsand/pre-commit-jvm#5]
When I run detekt with gradle, I configure it with a file with these contents: 

```
style:
  ForbiddenComment:
    active: true
    values: ['TODO:', 'FIXME:', 'STOPSHIP:']
    allowedPatterns: 'PROJECT-'
```

Detekt runs with the ForbiddenComment rule as I have configured it, and all other rules according to the default config.

When I run detekt with pre-commit, it replaces the config completely. This means that I only have one rule, ForbiddenComment. To solve this, I would need to specify the entire default config in my config file, which I don't want to do. Is it possible for the config to be interpreted as "additive/override" as opposed to "replace"?
